# -*- coding: utf-8 -*-
"""MLIA Lab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KeZnadF-EoAHE2WNTBVlImaldoYoC1Mm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error
from google.colab import files

sns.set_theme(style="whitegrid", font_scale=1.1)
plt.rcParams['figure.dpi'] = 150

print("Step 1: Uploading Files...")
uploaded = files.upload()
m_raw = pd.read_csv([f for f in uploaded.keys() if 'Monthly' in f][0], header=None)
q_raw = pd.read_csv([f for f in uploaded.keys() if 'Quarterly' in f][0], header=None)

def clean_num(series):
    return pd.to_numeric(series.astype(str).str.replace('%','').str.replace(',','').str.strip(), errors='coerce')

# Monthly Processing
m_df = pd.DataFrame()
m_df['Date'] = pd.to_datetime(m_raw.iloc[2:, 0], format='%b-%y', errors='coerce')
m_df['Wage_Growth'] = clean_num(m_raw.iloc[2:, 28])
m_df['CPI'] = clean_num(m_raw.iloc[2:, 40])
m_df['WPI'] = clean_num(m_raw.iloc[2:, 43])
m_df['Treasury_Yield'] = clean_num(m_raw.iloc[2:, 47])

iip_industries = []
for i in range(1, 28):
    name = f"IIP_{str(m_raw.iloc[1, i])[:25]}"
    iip_industries.append(name)
    m_df[name] = clean_num(m_raw.iloc[2:, i])

# Fill gaps and align to Quarter Ends
m_df = m_df.dropna(subset=['Date']).set_index('Date').interpolate(method='linear', limit_direction='both')
m_q_df = m_df.resample('Q').mean().reset_index()

# Quarterly Processing (Targets: 4 Sales + CC + House Prices | Features: Sentiment)
def parse_q_date(d):
    try: return pd.to_datetime(d, format='%b %Y')
    except: return pd.NaT

q_df = pd.DataFrame()
q_df['Date'] = q_raw.iloc[6:, 0].apply(parse_q_date)
q_df['CC_Transactions'] = clean_num(q_raw.iloc[6:, 1])
q_df['House_Prices'] = clean_num(q_raw.iloc[6:, 57])
q_df['Real_Estate_Sales'] = clean_num(q_raw.iloc[6:, 49])
q_df['Hotel_Sales'] = clean_num(q_raw.iloc[6:, 52])
q_df['Consumer_Goods_Sales'] = clean_num(q_raw.iloc[6:, 54])
q_df['Auto_Sales'] = clean_num(q_raw.iloc[6:, 56])
q_df['CCI_Current'] = clean_num(q_raw.iloc[6:, 72])
q_df['CCI_Future'] = clean_num(q_raw.iloc[6:, 76])
q_df = q_df.dropna(subset=['Date'])
q_df['Date'] = q_df['Date'] + pd.offsets.QuarterEnd(0)

# Merge into Master Table
master_df = pd.merge(q_df, m_q_df, on='Date', how='left').sort_values('Date')
features = ['CPI', 'WPI', 'Treasury_Yield', 'Wage_Growth', 'CCI_Current', 'CCI_Future']
master_df[features] = master_df[features].interpolate(method='linear', limit_direction='both')

all_targets = ['CC_Transactions', 'House_Prices', 'Real_Estate_Sales', 'Hotel_Sales', 'Consumer_Goods_Sales', 'Auto_Sales'] + iip_industries

# 2. ML ANALYSIS
final_results = []
print("\nAnalyzing 33 Outcomes across all parameters...")

for target in all_targets:
    best_features = []
    lags = {}
    for f in features:
        # Search for highest correlation across 18 months
        corrs = [abs(master_df[target].corr(master_df[f].shift(l))) for l in range(7)]
        best_l = np.argmax([c if not np.isnan(c) else 0 for c in corrs])
        lags[f] = int(best_l)
        best_features.append(master_df[f].shift(best_l).rename(f"{f}_L{best_l}"))

    ml_data = pd.concat([master_df[target]] + best_features, axis=1).dropna()
    if len(ml_data) < 5: continue

    X, y = ml_data.iloc[:, 1:], ml_data.iloc[:, 0]
    rf = RandomForestRegressor(n_estimators=150, random_state=42).fit(X, y)

    # Feature Significance Mapping
    imp_dict = {f.split('_L')[0]: rf.feature_importances_[i] for i, f in enumerate(X.columns)}

    # Elasticity Logic (Sum of Price/Rate sensitivity)
    price_sens = imp_dict.get('CPI', 0) + imp_dict.get('Treasury_Yield', 0)
    elasticity = "Elastic" if price_sens > 0.3 else "Inelastic"

    final_results.append({
        'Industry': target, 'R2': r2_score(y, rf.predict(X)), 'MAE': mean_absolute_error(y, rf.predict(X)),
        'Importances': imp_dict, 'Lags': lags, 'Elasticity': elasticity
    })

# 3. DETAILED VISUALS
plt.figure(figsize=(22, 20))

# Plot A: Full Sensitivity Heatmap
plt.subplot(2, 2, 1)
heat_df = pd.DataFrame({r['Industry']: r['Importances'] for r in final_results}).T
sns.heatmap(heat_df, annot=True, cmap="YlGnBu")
plt.title("Industry vs. Parameter Significance (33 Targets)", pad=20, weight='bold')

# Plot B: Average Lag Distribution (Months)
plt.subplot(2, 2, 2)
avg_lag_df = pd.DataFrame([r['Lags'] for r in final_results]).mean().sort_values() * 3
sns.barplot(x=avg_lag_df.index, y=avg_lag_df.values, palette="mako")
plt.title("Economic Transmission: Average Lag (Months) by Feature", pad=20, weight='bold')
plt.ylabel("Months")
plt.xticks(rotation=45)

# Plot C: Predictability (R2) by Sector
plt.subplot(2, 2, 3)
perf_df = pd.DataFrame(final_results).sort_values('R2', ascending=False)
sns.barplot(data=perf_df.head(15), x='R2', y='Industry', palette="viridis")
plt.title("Top 15 Most Predictable Outcomes (R-Squared)", pad=20, weight='bold')

# Plot D: Elasticity vs Inelasticity Count
plt.subplot(2, 2, 4)
elastic_counts = pd.Series([r['Elasticity'] for r in final_results]).value_counts()
sns.barplot(x=elastic_counts.index, y=elastic_counts.values, palette="Set2")
plt.title("Market Classification (Elastic vs Inelastic)", pad=20, weight='bold')

plt.tight_layout()
plt.show()

# 4. FINAL OUTPUT TABLES
print("\n" + "="*95)
print(f"{'INDUSTRY':<40} | {'R2':<6} | {'MAE':<8} | {'ELASTICITY':<12}")
print("="*95)
full_report = pd.DataFrame(final_results).sort_values('R2', ascending=False)
for _, row in full_report.iterrows():
    print(f"{row['Industry']:<40} | {row['R2']:<6.4f} | {row['MAE']:<8.4f} | {row['Elasticity']:<12}")

print("\n" + "="*95)
print(f"{'OUTCOME':<40} | {'BEST PARAMETER':<15} | {'LAG':<10}")
print("="*95)
for res in final_results:
    top_p = max(res['Importances'], key=res['Importances'].get)
    print(f"{res['Industry']:<40} | {top_p:<15} | {res['Lags'][top_p]*3} Months")